apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sss.fullname" . }}
  labels:
    {{- include "sss.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sss.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "sss.fullname" . | nindent 8 }}
      labels:
        {{- include "sss.selectorLabels" . | nindent 8 }}   
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/var/secrets"
            name: secrets
            readOnly: true
        envFrom:
          - configMapRef:
              name: {{ template "sss.fullname" . }}
        env:
{{- if not .Values.mountSecrets }}
  {{- if .Values.s3.accessKey }}
          - name: AWSSettings__AccessKey
            valueFrom:
              secretKeyRef:
                name: secrets-{{ template "sss.fullname" . }}
                key: s3-accesskey
  {{- end }}
  {{- if .Values.s3.secretKey }}
          - name: AWSSettings__SecretKey
            valueFrom:
              secretKeyRef:
                name: secrets-{{ template "sss.fullname" . }}
                key: s3-secretkey
  {{- end }}
{{- end }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          failureThreshold: 5
          successThreshold: 1
        readinessProbe:
          httpGet:
              path: /healthz
              port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
          failureThreshold: 5
          successThreshold: 1
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: secrets
          secret:
            secretName: secrets-{{ template "sss.fullname" . }}