{{- if eq .Values.inlets.enabled true }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.tunnel.pregentokenname }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.tunnel.token | b64enc | quote }}

{{- end}}