apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "agent.fullname" . }}-env
  labels:
    app: {{ template "agent.fullname" . }}
    chart: "{{ template "agent.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  {{- if .Values.PortForward__Range }}
  PortForward__Range: {{ .Values.PortForward__Range | quote }}
  {{- end }}
  {{- if .Values.jwtIssuer }}
  Jwt__Issuer: {{ .Values.jwtIssuer | quote }}
  {{- end }}

