
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.agents.imagePullSecretName }}
  labels:
    app: {{ template "agent.fullname" . }}
    chart: "{{ template "agent.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.agents.dockerconfigjson }}