{{- if and .Values.imageCredentials.registry .Values.imageCredentials.username .Values.imageCredentials.password }}

apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: regcred
  labels:
    app: {{ template "agent.fullname" . }}
    chart: "{{ template "agent.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}

{{- end }}
