{{- if eq .Values.inlets.enabled true }}

apiVersion: v1
kind: Secret
metadata:
  name: inlets-uplink-license
  labels:
    {{- include "agent.labels" . | nindent 4 }}
type: Opaque
data:
  license: {{ .Values.inlets.license | b64enc | quote }}

{{- end}}