# {{ $myvar := "Host={{ .Values.host }}; database={{ .Values.database }}; Username={{ .Values.auth.username }}; Password={{ .Values.auth.password }}; SearchPath={{ .Values.searchPath }}" }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "agent.fullname" . }}
  labels:
    app: {{ template "agent.fullname" . }}
    chart: "{{ template "agent.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"

stringData:
  ConnectionStrings__AgentsDatabase: Host={{ .Values.database.host }}; database={{ .Values.database.database_name }}; Username={{ .Values.database.auth.username }}; Password={{ .Values.database.auth.password }}; SearchPath={{ .Values.database.searchPath }} 
  {{- if .Values.clientId }}
  DefaultApiClient__ClientId: {{ .Values.clientId | quote}}
  {{- end }}
  {{- if .Values.clientSecret }}
  DefaultApiClient__ClientSecret: {{ .Values.clientSecret | quote }}
  {{- end }}


