apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "agent.fullname" . }}
  labels:
    app: {{ template "agent.fullname" . }}
    chart: "{{ template "agent.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"

data:
  {{- if and .Values.agents.database.host .Values.agents.database.name .Values.agents.database.schema .Values.agents.database.auth.username .Values.agents.database.auth.password }}
  ConnectionStrings__AgentsDatabase: {{ printf "Host=%s; Database=%s; SearchPath=%s; Username=%s; Password=%s" .Values.agents.database.host .Values.agents.database.name .Values.agents.database.schema .Values.agents.database.auth.username .Values.agents.database.auth.password | b64enc | quote }}
  {{- end }}
  {{- if .Values.agents.clientId }}
  DefaultApiClient__ClientId: {{ .Values.agents.clientId | b64enc | quote}}
  {{- end }}
  {{- if .Values.agents.clientSecret }}
  DefaultApiClient__ClientSecret: {{ .Values.agents.clientSecret | b64enc | quote }}
  {{- end }}


