apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ template "agent.fullname" . }}
  labels:
    app: {{ template "agent.fullname" . }}
    chart: "{{ template "agent.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  {{- if .Values.agents.database.ConnectionStrings__AgentsDatabase }}
  ConnectionStrings__AgentsDatabase: {{ .Values.agents.database.ConnectionStrings__AgentsDatabase | b64enc | quote }}
  {{- end }}
  {{- if .Values.agents.database.DefaultApiClient__ClientId }}
  DefaultApiClient__ClientId: {{ .Values.agents.database.DefaultApiClient__ClientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.agents.database.DefaultApiClient__ClientSecret }}
  DefaultApiClient__ClientSecret: {{ .Values.agents.database.DefaultApiClient__ClientSecret | b64enc | quote }}
  {{- end }}


