{{- if eq .Values.inlets.enabled true }}

apiVersion: uplink.inlets.dev/v1alpha1
kind: Tunnel
metadata:
  name: {{ .Values.tunnel.tunnelname }}
  namespace: {{ .Release.Namespace }}
spec:
  licenseRef: 
    name: inlets-uplink-license
    namespace: {{ .Release.Namespace }}
  tokenRef:
    name: {{ .Values.tunnel.pregentokenname }}
    namespace: {{ .Release.Namespace }}
  tcpPorts:
  - 8080
  - 5001
{{- with .Values.tunnel.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 8 }}
{{- end }}

{{- end }}
