{{- if eq .Values.inlets.enabled true }}

apiVersion: uplink.inlets.dev/v1alpha1
kind: Tunnel
metadata:
  name: {{ .Values.tunnel.tunnelname }}
  namespace: {{ .Release.Namespace }}
spec:
  licenseRef: 
    name: inlets-uplink-license
    namespace: {{ .Release.Namespace }}
{{- if .Values.tunnel.token }}
  tokenRef:
    name: {{ .Values.tunnel.pregentokenname }}
    token: {{ .Values.tunnel.token }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- with .Values.tunnel.tcpPorts }}
  tcpPorts:
{{- range untilStep (.Values.tunnel.tcpPorts.lower | int) (.Values.tunnel.tcpPorts.higher | int) 1}}
    - {{ . }}
{{- end }}
{{- with .Values.tunnel.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 8 }}
{{- end }}

{{- end }}