apiVersion: v1
kind: Service
metadata:
  name: {{ include "eoc-backend.fullname" . }}-service
{{- if .Values.backend.metrics.enabled }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '3000'
    prometheus.io/path: {{ .Values.backend.basePath }}/metrics
{{- end }}  
spec:
  ports:
    - name: {{ include "eoc-backend.fullname" . }}-service-port
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    {{- include "eoc-backend.selectorLabels" . | nindent 4 }}