{{- if not .Values.backend.sealedSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: secrets-{{ template "eoc-backend.fullname" . }}
  labels:
    {{- include "eoc-backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.backend.database.auth.user }}
  database-auth-user:  {{ .Values.backend.database.auth.user | b64enc | quote }}
  {{- end }}
  {{- if .Values.backend.database.auth.pass }}
  database-auth-pass:  {{ .Values.backend.database.auth.pass | b64enc | quote }}
  {{- end }}

  {{- if .Values.backend.jwt.secret }}
  jwt-secret:  {{ .Values.backend.jwt.secret | b64enc | quote }}
  {{- end }}

  {{- if .Values.backend.oauth.google.clientId }}
  oauth-google-clientid:  {{ .Values.backend.oauth.google.clientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.backend.oauth.google.clientSecret }}
  oauth-google-clientsecret:  {{ .Values.backend.oauth.google.clientSecret | b64enc | quote }}
  {{- end }}

  {{- if .Values.backend.oauth.github.clientId }}
  oauth-github-clientid:  {{ .Values.backend.oauth.github.clientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.backend.oauth.github.clientSecret }}
  oauth-github-clientsecret:  {{ .Values.backend.oauth.github.clientSecret | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.backend.oauth.microsoft.clientId }}
  oauth-microsoft-clientid:  {{ .Values.backend.oauth.microsoft.clientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.backend.oauth.microsoft.clientSecret }}
  oauth-microsoft-clientsecret:  {{ .Values.backend.oauth.microsoft.clientSecret | b64enc | quote }}
  {{- end }}
  
  {{- if .Values.backend.smtp.user }}
  smtp-user:  {{ .Values.backend.smtp.user | b64enc | quote }}
  {{- end }}
  {{- if .Values.backend.smtp.pass }}
  smtp-pass:  {{ .Values.backend.smtp.pass | b64enc | quote }}
  {{- end }}

  {{- if .Values.backend.encryptionKey }}
  encryption-key:  {{ .Values.backend.encryptionKey | b64enc | quote }}
  {{- end }}

  {{- if .Values.backend.grafana.username }}
  grafana-username:  {{ .Values.backend.grafana.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.backend.grafana.password }}
  grafana-password:  {{ .Values.backend.grafana.password | b64enc | quote }}
  {{- end }}

  {{- if .Values.backend.agents.api.clientId }}
  agents-api-clientid:  {{ .Values.backend.agents.api.clientId | b64enc | quote }}
  {{- end }}
  {{- if .Values.backend.agents.api.clientSecret }}
  agents-api-clientsecret:  {{ .Values.backend.agents.api.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.backend.agents.inlets.token }}
  agents-inlets-token:  {{ .Values.backend.agents.inlets.token | b64enc | quote }}
  {{- end }}
{{- end }}