apiVersion: v1
data:
  APP_BASE_PATH: {{ .Values.backend.basePath | quote }}

  UI_BASE_URL: {{ printf "%s%s" .Values.ui.auth.loginReturnUrl .Values.ui.basePath | quote }}
  S3_BUCKET_NAME: {{ .Values.backend.s3BucketName | quote  }}
  DUPLO_SERVICES_TENANT_NAME: {{ .Values.orchestrator.duplo.servicesTenantName | quote }}

  BULL_REDIS_URL: {{ .Values.backend.redis.bullUrl | quote }}
  REDIS_HOST: {{ .Values.backend.redis.host | quote }}
  REDIS_PORT: {{ .Values.backend.redis.port | quote }}

  DATABASE_NAME: {{ .Values.backend.database.name | quote }}
  DATABASE_SCHEMA: {{ .Values.backend.database.schema | quote }}
  DATABASE_HOST: {{ .Values.backend.database.host | quote }}
  DATABASE_PORT: {{ .Values.backend.database.port | quote }}

  JWT_EXPIRES_IN: {{ .Values.backend.jwt.expiresIn | quote }}

  EMAIL_FROM: {{ .Values.backend.smtp.from | quote }}
  EMAIL_HOST: {{ .Values.backend.smtp.host | quote }}
  EMAIL_PORT: {{ .Values.backend.smtp.port | quote }}

  ADMIN_EMAIL: {{ .Values.backend.admin.email | quote }}
  ADMIN_FIRST_NAME: {{ .Values.backend.admin.firstName | quote }}
  ADMIN_LAST_NAME: {{ .Values.backend.admin.lastName | quote }}

  APP_ROOT_DIRECTORY: {{ .Values.backend.appRootDirectory | quote }}

  KIBANA_API_LINK: {{ .Values.backend.kibana.apiUrl | quote }}

  GRAFANA_BASE_URL: {{ .Values.backend.grafana.host | quote }}

  AGENTS_BASE_PATH: {{ .Values.backend.agents.api.endpoint | quote }}
  AGENTS_SERVER_NAME: {{ .Values.backend.agents.inlets.serverName | quote }}
  AGENTS_SERVER_ENDPOINT: {{ .Values.backend.agents.inlets.serverEndpoint | quote }}

  MIN_ENVIRONMENT_VERSION: {{ .Values.global.minFidVersion | quote }}
  ENV_PREFIX: {{ .Values.global.infrastructureName | quote }}
  DOMAIN_NAME: {{ .Values.global.domainName | quote }}

  NODE_LIMIT: {{ .Values.global.nodeLimit | quote }}
kind: ConfigMap
metadata:
  labels:
    role: eoc-backend
  name: {{ template "eoc-backend.fullname" . }}
  labels:
    app: {{ template "eoc-backend.fullname" . }}
    chart: "{{ template "eoc-backend.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
