apiVersion: v1
data:
  APP_BASE_PATH: {{ .Values.backend.basePath | quote }}

  UI_BASE_URL: {{ printf "%s%s" .Values.ui.auth.loginReturnUrl .Values.ui.basePath | quote }}
  S3_BUCKET_NAME: {{ .Values.backend.s3BucketName | quote  }}
  DUPLO_SERVICES_TENANT_NAME: {{ .Values.orchestrator.duplo.servicesTenantName | quote }}

  BULL_REDIS_URL: {{ .Values.backend.redis.bullUrl | quote }}
  REDIS_HOST: {{ .Values.backend.redis.host | quote }}
  REDIS_PORT: {{ .Values.backend.redis.port | quote }}

  DATABASE_NAME: {{ .Values.backend.database.name | quote }}
  DATABASE_SCHEMA: {{ .Values.backend.database.schema | quote }}
  DATABASE_HOST: {{ .Values.backend.database.host | quote }}
  DATABASE_PORT: {{ .Values.backend.database.port | quote }}
  DATABASE_USERNAME: {{ .Values.backend.database.auth.user | quote }}
  DATABASE_PASSWORD: {{ .Values.backend.database.auth.pass | quote }}

  ENABLE_MFA: {{ .Values.features.mfa.enabled | quote }}
  APP_MFA_NAME: {{ .Values.features.mfa.appName | quote }}

  JWT_SECRET: {{ .Values.backend.jwt.secret | quote }}
  JWT_EXPIRES_IN: {{ .Values.backend.jwt.expiresIn | quote }}

  OAUTH_GOOGLE_ENABLE: {{ .Values.backend.oauth.google.enabled | quote }}
  OAUTH_GOOGLE_CLIENT_ID: {{ .Values.backend.oauth.google.clientId | quote }}
  OAUTH_GOOGLE_CLIENT_SECRET: {{ .Values.backend.oauth.google.clientSecret | quote }}

  OAUTH_GITHUB_ENABLE: {{ .Values.backend.oauth.github.enabled | quote }}
  OAUTH_GITHUB_CLIENT_ID: {{ .Values.backend.oauth.github.clientId | quote }}
  OAUTH_GITHUB_CLIENT_SECRET: {{ .Values.backend.oauth.github.clientSecret | quote }}

  OAUTH_MICROSOFT_ENABLE: {{ .Values.backend.oauth.microsoft.enabled | quote }}
  OAUTH_MICROSOFT_CLIENT_ID: {{ .Values.backend.oauth.microsoft.clientId | quote }}
  OAUTH_MICROSOFT_CLIENT_SECRET: {{ .Values.backend.oauth.microsoft.clientSecret | quote }}

  AUTH_LOCAL_ENABLE: {{ .Values.backend.oauth.local.enabled | quote }}

  EMAIL_FROM: {{ .Values.backend.smtp.from | quote }}
  EMAIL_ID: {{ .Values.backend.smtp.user | quote }}
  EMAIL_PASS: {{ .Values.backend.smtp.pass | quote }}
  EMAIL_HOST: {{ .Values.backend.smtp.host | quote }}
  EMAIL_PORT: {{ .Values.backend.smtp.port | quote }}

  ADMIN_EMAIL: {{ .Values.backend.admin.email | quote }}
  ADMIN_FIRST_NAME: {{ .Values.backend.admin.firstName | quote }}
  ADMIN_LAST_NAME: {{ .Values.backend.admin.lastName | quote }}

  APP_ROOT_DIRECTORY: {{ .Values.backend.appRootDirectory | quote }}

  ENCRYPTION_KEY: {{ .Values.backend.encryptionKey | quote }}

  KIBANA_API_LINK: {{ .Values.backend.kibana.apiUrl | quote }}

  GRAFANA_BASE_URL: {{ .Values.backend.grafana.host | quote }}
  GRAFANA_USERNAME: {{ .Values.backend.grafana.username | quote }}
  GRAFANA_PASSWORD: {{ .Values.backend.grafana.password | quote }}
  GRAFANA_METRICS_PREFIXES: {{ .Values.backend.grafana.metricsPrefixes | quote }}

  AGENTS_BASE_PATH: {{ .Values.backend.agents.api.endpoint | quote }}
  AGENTS_CLIENT_ID: {{ .Values.backend.agents.api.clientId | quote }}
  AGENTS_CLIENT_SECRET: {{ .Values.backend.agents.api.clientSecret | quote }}
  AGENTS_INLETS_TOKEN: {{ .Values.backend.agents.inlets.token | quote }}
  AGENTS_SERVER_NAME: {{ .Values.backend.agents.inlets.serverName | quote }}
  AGENTS_SERVER_ENDPOINT: {{ .Values.backend.agents.inlets.serverEndpoint | quote }}
  SDC_AWS_ACCESS_KEY_ID: {{ .Values.backend.agents.client.accessKeyId | quote}}
  SDC_AWS_ACCESS_KEY_SECRET: {{ .Values.backend.agents.client.accessKeySecret | quote }}
  SDC_AWS_REGION: {{ .Values.backend.agents.client.s3Region | quote }}
  SDC_AWS_S3_BUCKET_NAME: {{ .Values.backend.agents.client.s3BucketName | quote }}
  SDC_CLIENT_VERSION: {{ .Values.backend.agents.client.version | quote }}

  MIN_ENVIRONMENT_VERSION: {{ .Values.global.minFidVersion | quote }}
  ENV_PREFIX: {{ .Values.global.infrastructureName | quote }}
  DOMAIN_NAME: {{ .Values.global.domainName | quote }}

  NODE_LIMIT_FID: {{ .Values.applications.fid.nodeLimit | default 1 | quote }}
  NODE_LIMIT_BRAINWAVE: {{ .Values.applications.brainwave.nodeLimit | default 1 | quote }}
  FID_MIN_VERSION: {{ .Values.applications.fid.minVersion | default .Values.global.minFidVersion | default "8.0.0" | quote }}
  BW_MIN_VERSION: {{ .Values.applications.brainwave.minVersion | default "2.0.0" | quote }}

  DUPLO_SERVICES_NAMESPACE: {{  .Values.global.commonServicesNamespace | default .Values.orchestrator.duplo.servicesTenantName | quote }}
  ENVIRONMENT_NAMESPACE_PREFIX: {{ .Values.global.environmentNamespacePrefix | default "" | quote }}
{{- range $key, $value := (.Values.backend).env }}
  {{ tpl $key $ }}: {{ tpl (print $value) $ | quote }}
{{- end }}
{{- range $key, $value := (.Values.global).env }}
  {{ tpl $key $ }}: {{ tpl (print $value) $ | quote }}
{{- end }}
kind: ConfigMap
metadata:
  labels:
    role: eoc-backend
  name: {{ template "eoc-backend.fullname" . }}
  labels:
    app: {{ template "eoc-backend.fullname" . }}
    chart: "{{ template "eoc-backend.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
