apiVersion: v1
data:
  REGION: {{ .Values.global.region | quote }}
  DOMAIN_NAME: {{ .Values.global.domainName | quote }}
  CERTIFICATE_ARN: {{ .Values.global.certificateArn | quote }}
  REDIS_HOST: {{ .Values.orchestrator.redis.host | quote }}
  REDIS_PORT: {{ .Values.orchestrator.redis.port | quote }}
  DUPLO_PLAN_ID: {{ .Values.global.infrastructureName | quote }}
  DUPLO_TOKEN: {{ .Values.orchestrator.duplo.token | quote }}
  DUPLO_BASE_URL: {{ .Values.orchestrator.duplo.baseUrl | quote }}
  DUPLO_SERVICES_TENANT_NAME: {{ .Values.orchestrator.duplo.servicesTenantName | quote }}
  DUPLO_ZONES: {{ .Values.global.zones | quote }}
  DUPLO_AMI_IMAGE_ID: {{ .Values.global.amiImageId | quote }}
  ARGO_CD_BASE_URL: {{ .Values.orchestrator.argocd.baseUrl | quote }}
  ARGO_CD_TOKEN: {{ .Values.orchestrator.argocd.token | quote }}
  FID_LICENSE_KEY: {{ .Values.global.fidLicense | quote }}
  GIT_REPO: {{ .Values.orchestrator.git.repo | quote }}
  GIT_PRIVATE_KEY: {{ .Values.orchestrator.git.privateKey | quote }}
  REDIS_HOST: {{ .Values.orchestrator.redis.host | quote }}
  REDIS_PORT: {{ .Values.orchestrator.redis.port | quote }}
  ENCRYPTION_KEY: {{ .Values.backend.encryptionKey | quote }}
  APP_GIT_REPO: {{ .Values.applications.fid.pipelineConfig.git.repo | quote }}
  APP_GIT_PRIVATE_KEY: {{ .Values.applications.fid.pipelineConfig.git.privateKey | quote }}
  DUPLO_SERVICES_NAMESPACE: {{  .Values.global.commonServicesNamespace | default .Values.orchestrator.duplo.servicesTenantName | quote }}
  ENVIRONMENT_NAMESPACE_PREFIX: {{ .Values.global.environmentNamespacePrefix | quote }}
  GRAFANA_BASIC_AUTH: {{ .Values.backend.grafana.basicAuth | default "" | quote }}
{{- range $key, $value := (.Values.orchestrator).env }}
  {{ tpl $key $ }}: {{ tpl (print $value) $ | quote }}
{{- end }}
{{- range $key, $value := (.Values.global).env }}
  {{ tpl $key $ }}: {{ tpl (print $value) $ | quote }}
{{- end }}
kind: ConfigMap
metadata:
  labels:
    role: eoc-orchestrator
  name: {{ template "eoc-orchestrator.fullname" . }}
  labels:
    app: {{ template "eoc-orchestrator.fullname" . }}
    chart: "{{ template "eoc-orchestrator.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
