apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eoc-orchestrator.fullname" . }}
  labels:
    {{- include "eoc-orchestrator.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "eoc-orchestrator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "eoc-orchestrator.fullname" . | nindent 8 }}
      labels:
        {{- include "eoc-orchestrator.selectorLabels" . | nindent 8 }}   
      annotations:
      {{- if (.Values.checksumConfigMap).enabled | default true }}
        checksum/environment: {{ include (print $.Template.BasePath "/orchestrator_configmap.yaml") . | sha256sum }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.orchestrator.image.repository }}:{{ .Values.orchestrator.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.orchestrator.image.pullPolicy }}
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: {{ template "eoc-orchestrator.fullname" . }}
        readinessProbe:
          tcpSocket:
            port: 3001
          initialDelaySeconds: {{ default 60 .Values.orchestrator.initialDelaySeconds }}
          periodSeconds: {{ default 30 .Values.orchestrator.periodSeconds }}
          failureThreshold: 5
          successThreshold: 1
        livenessProbe:
          tcpSocket:
            port: 3001
          initialDelaySeconds: {{ default 60 .Values.orchestrator.initialDelaySeconds }}
          periodSeconds: {{ default 30 .Values.orchestrator.periodSeconds }}
          failureThreshold: 5
          successThreshold: 1
      serviceAccount: eoc-orchestrator
      {{- with .Values.orchestrator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.orchestrator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.orchestrator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
