apiVersion: v1
data:
  VITE_BASE_PATH: {{ .Values.ui.basePath | quote }}
  VITE_BASE_URL: {{ .Values.ui.apiBaseUrl | quote }}
  VITE_TOKEN_STORE_KEY: {{ .Values.ui.auth.tokenStoreKey | quote }}
  VITE_LOGIN_URL: {{ .Values.ui.auth.loginReturnUrl | quote }}
  VITE_DUPLO_PLAN_NAME: {{ default .Values.global.infrastructureName .Values.ui.infrastructureName | quote }}
  VITE_LOGGING_URL: {{ .Values.ui.loggingUrl | quote }}
  VITE_REPORTING_URL: {{ .Values.ui.reportingDashboardUrl | quote }}
  VITE_MONITORING_URL: {{ .Values.ui.monitoringDashboardUrl | quote }}
  VITE_KIBANA_API_PATH: {{ .Values.ui.kibanaApiPath | quote }}
  VITE_AMPLITUDE_KEY: {{ .Values.ui.amplitude.key | quote }}
  VITE_GOOGLE_AUTH_ENABLED: {{ .Values.backend.oauth.google.enabled | quote }}
  VITE_GITHUB_AUTH_ENABLED: {{ .Values.backend.oauth.github.enabled | quote }}
  VITE_LOCAL_AUTH_ENABLED: {{ .Values.backend.oauth.local.enabled | quote }}
  VITE_MICROSOFT_AUTH_ENABLED: {{ .Values.backend.oauth.microsoft.enabled | quote }}
  VITE_INSERT_MONITORING_JWT_TOKEN: {{ .Values.ui.insertMonitoringJwtToken | default false | quote }}
  VITE_TIERS_ENABLED: {{ .Values.ui.tiersVisibility | default false | quote }}
  VITE_MULTI_TENANT_ENABLED: {{ .Values.ui.multiTenantEnabled | default false | quote }}
  VITE_SERVICE_STATUS_ENABLED: {{ .Values.ui.serviceStatusEnabled | default false | quote }}
  VITE_SCHEDULED_MAINTENANCE_ENABLED: {{ .Values.ui.scheduledMaintenanceEnabled | default false | quote }}
  VITE_IDO_ENABLED: {{ .Values.applications.ido.enabled | default false | quote }}
  VITE_TASK_MANAGEMENT_LOGS_ENABLED: {{ .Values.ui.taskManagementLogsEnabled | default false | quote }}
  VITE_TASK_MANAGEMENT_RE_RUN_ENABLED: {{ .Values.ui.taskManagementReRunEnabled | default false | quote }}
  VITE_TASK_MANAGEMENT_CANCEL_ENABLED: {{ .Values.ui.taskManagementCancelEnabled | default false | quote }}
  VITE_PROMOTION_PIPELINES_ENABLED: {{ .Values.features.pipeline.enabled | default false | quote }}
{{- range $key, $value := (.Values.ui).env }}
  {{ tpl $key $ }}: {{ tpl (print $value) $ | quote }}
{{- end }}
{{- range $key, $value := (.Values.global).env }}
  {{ tpl $key $ }}: {{ tpl (print $value) $ | quote }}
{{- end }}
kind: ConfigMap
metadata:
  labels:
    role: eoc-ui
  name: {{ template "eoc-ui.fullname" . }}
  labels:
    app: {{ template "eoc-ui.fullname" . }}
    chart: "{{ template "eoc-ui.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
