apiVersion: v1
data:
  VITE_BASE_PATH: {{ .Values.ui.basePath | quote }}
  VITE_BASE_URL: {{ .Values.ui.apiBaseUrl | quote }}
  VITE_TOKEN_STORE_KEY: {{ .Values.ui.auth.tokenStoreKey | quote }}
  VITE_LOGIN_URL: {{ .Values.ui.auth.loginReturnUrl | quote }}
  VITE_DUPLO_PLAN_NAME: {{ default .Values.global.infrastructureName .Values.ui.infrastructureName | quote }}
  VITE_LOGGING_URL: {{ .Values.ui.loggingUrl | quote }}
  VITE_REPORTING_URL: {{ .Values.ui.reportingDashboardUrl | quote }}
  VITE_MONITORING_URL: {{ .Values.ui.monitoringDashboardUrl | quote }}
  VITE_KIBANA_API_PATH: {{ .Values.ui.kibanaApiPath | quote }}
  VITE_PROD_ENV_LIMIT: {{ .Values.global.prodEnvLimit | quote }}
  VITE_NONPROD_ENV_LIMIT: {{ .Values.global.nonprodEnvLimit | quote }}
kind: ConfigMap
metadata:
  labels:
    role: eoc-ui
  name: {{ template "eoc-ui.fullname" . }}
  labels:
    app: {{ template "eoc-ui.fullname" . }}
    chart: "{{ template "eoc-ui.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"