apiVersion: v1
data:
  VITE_BASE_PATH: {{ .Values.ui.basePath | quote }}
  VITE_BASE_URL: {{ .Values.ui.apiBaseUrl | quote }}
  VITE_TOKEN_STORE_KEY: {{ .Values.ui.auth.tokenStoreKey | quote }}
  VITE_LOGIN_URL: {{ .Values.ui.auth.loginReturnUrl | quote }}
  VITE_DUPLO_PLAN_NAME: {{ default .Values.global.infrastructureName .Values.ui.infrastructureName | quote }}
  VITE_LOGGING_URL: {{ .Values.ui.loggingUrl | quote }}
  VITE_REPORTING_URL: {{ .Values.ui.reportingDashboardUrl | quote }}
  VITE_MONITORING_URL: {{ .Values.ui.monitoringDashboardUrl | quote }}
  VITE_KIBANA_API_PATH: {{ .Values.ui.kibanaApiPath | quote }}
  VITE_AMPLITUDE_KEY: {{ .Values.ui.amplitude.key | quote }}
  VITE_GOOGLE_AUTH_ENABLED: {{ .Values.backend.oauth.google.enabled | default true | quote }}
  VITE_GITHUB_AUTH_ENABLED: {{ .Values.backend.oauth.github.enabled | default true | quote }}
  VITE_MICROSOFT_AUTH_ENABLED: {{ .Values.backend.oauth.microsoft.enabled | default true | quote }}
{{- range $key, $value := (.Values.ui).env }}
  {{ tpl $key $ }}: {{ tpl (print $value) $ | quote }}
{{- end }}  
{{- range $key, $value := (.Values.global).env }}
  {{ tpl $key $ }}: {{ tpl (print $value) $ | quote }}
{{- end }}  
kind: ConfigMap
metadata:
  labels:
    role: eoc-ui
  name: {{ template "eoc-ui.fullname" . }}
  labels:
    app: {{ template "eoc-ui.fullname" . }}
    chart: "{{ template "eoc-ui.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
