apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eoc-ui.fullname" . }}
  labels:
    {{- include "eoc-ui.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "eoc-ui.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      name: {{ include "eoc-ui.fullname" . | nindent 8 }}
      labels:
        {{- include "eoc-ui.selectorLabels" . | nindent 8 }}   
      annotations:
      {{- if (.Values.checksumConfigMap).enabled | default true }}
        checksum/environment: {{ include (print $.Template.BasePath "/ui_configmap.yaml") . | sha256sum }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: {{ template "eoc-ui.fullname" . }}
        livenessProbe:
          httpGet:
            path: /eoc/login
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 30
          failureThreshold: 10
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /eoc/login
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 30
          failureThreshold: 10
          successThreshold: 1
      {{- with .Values.ui.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.ui.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
