
nodeSelector:
  tenantname: xxxxx

agents:
  database:
    ConnectionStrings__AgentsDatabase: "Host=postgresql; Database=agentsdb; Username=agentsadmin; Password=xxxxx; SearchPath=agents"
    DefaultApiClient__ClientId: "xxxxx"
    DefaultApiClient__ClientSecret: "xxxxx"
  jwtIssuer: "OPAServer"
  imagePullSecretName: regcred
  dockerconfigjson: "xxxxx"

tunnel:
  tunnelname: r1tunnel
  nodeSelector:
    tenantname: xxxxx
  token: "xxxxx"
  pregentokenname: "pregentoken"

inlets:
  license: "xxxxx"
  # A router to work on a wildcard domain and to direct
  # traffic according to request domain
  clientRouter:
    # Customer tunnels will connect with a URI of:
    # wss://uplink.example.com/namespace/tunnel
    domain: uuplink.example.com/namespace/tunnel

postgresql:
  enabled: false
