{{- if .Values.agents }}
# Create ConfigMaps for each agent
{{- range .Values.agents }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent.fullname.agent" (dict "root" $ "agentName" .name) }}-env
  labels:
    app: {{ include "agent.fullname.agent" (dict "root" $ "agentName" .name) }}
    chart: "{{ template "agent.chart" $ }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
    agent-name: {{ .name }}
data:
  ServerHubConfiguration__AgentToken: {{ .token | quote }}
{{- end }}
{{- end }}
