apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "agent.fullname" . }}-env
  labels:
    app: {{ template "agent.fullname" . }}
    chart: "{{ template "agent.chart" . }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  {{- if .Values.agent.token }}
  ServerHubConfiguration__AgentToken: {{ .Values.agent.token | quote }}
  {{- end }}

