name: Lint and Test EOC Charts

on:
  pull_request:
    paths:
      - 'charts/eoc/**'

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:

      - name: Clear any existing tool cache
        run: |
          mv "${{ runner.tool_cache }}" "${{ runner.tool_cache }}.old"
          mkdir -p "${{ runner.tool_cache }}"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.9.2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.3.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add radiantone https://radiantlogic-devops.github.io/helm-charts

      - name: Run chart-testing (lint)
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'

      - name: Kind cluster-info
        run: |
          kubectl cluster-info --context kind-chart-testing
          kubectl get nodes --context kind-chart-testing

      - name: Create temporary values file
        run: |
          cat << EOF > temp-values.yaml
          backend:
            releaseChannels:
              - name: "Official"
                url: "https://radiantlogic-devops.github.io/release-stable/index.yaml"
                isDefault: "true"
            tiers:
              - name: BaseTier
                asg:
                  Capacity: m5a.large
                  DesiredCapacity: 1
                  MinSize: 0
                  MaxSize: 3
                  MetaData:
                  - Key: OsDiskSize
                    Value: 50Gi
                bwigrc:
                  resources:
                    limits:
                      cpu: 1
                      memory: 4Gi
                    requests:
                      cpu: 1
                      memory: 4Gi
                fid:
                  persistence:
                    enabled: true
                    size: 100Gi
                    storageClass: gp3
                  resources:
                    limits:
                      cpu: 1
                      memory: 4Gi
                    requests:
                      cpu: 1
                      memory: 4Gi
              - name: Tier1
                asg:
                  Capacity: m5a.xlarge
                bwigrc:
                  resources:
                    limits:
                      cpu: 2
                      memory: 8Gi
                fid:
                  persistence:
                    size: 100Gi
                  resources:
                    limits:
                      cpu: 2
                      memory: 8Gi
                    requests:
                      cpu: 2
                      memory: 8Gi
          EOF

      - name: Run chart-testing (install)
        run: |
          ct install --charts=charts/eoc --debug --helm-extra-args="--timeout=15m0s" --helm-extra-set-args="--set=postgresql.enabled=true \
                      --set=backend.database.auth.pass=eocadmin --set=backend.oauth.google.clientId=xxxxxx \
                      --set=backend.oauth.microsoft.enabled=true --set=backend.oauth.microsoft.clientSecret=xxxxxx --set=backend.oauth.microsoft.clientId=xxxxxx \
                      --set=backend.oauth.google.enabled=true --set=backend.oauth.google.clientSecret=xxxxxx --set=backend.oauth.github.clientId=xxxxxx \
                      --set=backend.oauth.github.enabled=true --set=backend.s3BucketName=r1-eoc --set=backend.grafana.metricsPrefixes=ldap \
                      --set=backend.oauth.local.enabled=true --set=features.mfa.enabled=false --set=features.mfa.appName=Radiant-Logic-EOC \
                      --set=applications.fid.nodeLimit=2 --set=applications.brainwave.nodeLimit=2 \
                      --set=applications.fid.minVersion=xxx --set=applications.brainwave.minVersion=xxx \
                      --set=global.commonServicesNamespace=xxxx --set=global.environmentNamespacePrefix=xxxx \
                      --set=sss.s3.bucketName=r1-eoc --set=sss.s3.region=us-west-2 \
                      --values temp-values.yaml" --upgrade